name: Screenshot Website

on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 9 * * *"

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Get pages URL
        id: pages_url
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "::set-output name=url::https://${{ github.repository_owner }}.github.io/$REPO_NAME/"

      - name: Generate screenshot
        id: "screenshot"
        uses: natainditama/screen-snap@main
        with:
          url: "${{ steps.pages_url.outputs.url }}"
          fileName: ".github/screnshot.png"

      - name: Commit changes 
        # Only run this step if screenshot path is not empty
        if: steps.screenshot.outputs.path != ''  
        uses: EndBug/add-and-commit@v9
        with:
          message: "docs: update ${{ steps.screenshot.outputs.path }}"
          add: "${{ steps.screenshot.outputs.path }}"
          author_email: natainditama.dev@gmail.com
          author_name: Nata Inditama
          committer_email: natainditama.dev@gmail.com
          committer_name: Nata Inditama
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
